# Generated by Django 2.0.5 on 2018-06-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mountains',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('code', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
