# Generated by Django 2.0.5 on 2018-06-08 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbnotify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('sex', models.CharField(max_length=16)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='mountains',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AddField(
            model_name='climbingrecord',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climbnotify.User'),
        ),
    ]
