# Generated by Django 2.0.5 on 2018-06-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbnotify', '0002_auto_20180608_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=16),
        ),
    ]
