# Generated by Django 2.0.5 on 2018-06-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbnotify', '0004_activatedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activatedusers',
            name='user_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='climbingrecord',
            name='user_id',
            field=models.CharField(max_length=64),
        ),
    ]
