# Generated by Django 2.0.5 on 2018-06-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbnotify', '0006_mappositiondata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappositiondata',
            name='id',
        ),
        migrations.AddField(
            model_name='mappositiondata',
            name='district_code',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
        ),
    ]
