# Generated by Django 2.0.5 on 2018-06-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbnotify', '0008_auto_20180611_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='activatedusers',
            name='mountain_info',
            field=models.CharField(default=-1, max_length=64),
        ),
    ]
