# Generated by Django 2.0.5 on 2018-06-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbnotify', '0009_activatedusers_mountain_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='activatedusers',
            name='climbing_date',
            field=models.CharField(default='', max_length=8),
        ),
    ]
